package ohos_app_cangjie_entry.ohos_app_cangjie_entry.common

public let foodikeThemePrimaryColor: Int64 = 0xFF59D173
public let foodikeThemePrimaryVariantColor: Int64 = 0xFF3700B3
public let foodikeThemeSecondaryColor: Int64 = 0xFF228D39
public let foodikeThemeSmallCornerRadius: Int64 = 4
public let foodikeThemeMediumCornerRadius: Int64 = 4
public let foodikeThemeLargeCornerRadius: Int64 = 0
public let foodikeThemeBodyFontSize: Int64 = 16
public let foodikeThemeUsesLightPalette: Bool = true
