[package]
cjc-version = "1.1.0"
compile-option = "--dy-std"
description = "CangjieUI Application Test"
link-option = "--unresolved-symbols=ignore-all"
name = "com_example_foodike_test"
output-type = "dynamic"
src-dir = "./src/ohosTest/cangjie"
target-dir = ""
version = "1.0.0"
package-configuration = {}
scripts = {}

[dependencies.ohos_app_cangjie_entry]
  path = "../../../"
  version = "1.0.0"

[profile]
  [profile.build]
    incremental = true
    lto = ""
  [profile.customized-option]
    debug = "-g -Woff all -Won apilevel-check"
    release = "--fast-math -O2 -s -Woff all -Won apilevel-check"
  [profile.test]
